import js from "@eslint/js";
import globals from "globals";
import reactHooks from "eslint-plugin-react-hooks";
import reactRefresh from "eslint-plugin-react-refresh";
import tseslint from "typescript-eslint";

export default tseslint.config(
  {
    // `supabase/functions` is Deno code that Lovable generates and regenerates:
    // `mcp/index.ts` is 651 auto-generated lines, and every fix we made there
    // would be gone after the next regeneration. It is also not built by Vite
    // and not covered by our tsconfig. `src/integrations/supabase` is
    // generated by the same hand, for the same reason. What matters about that
    // folder is who imports it, and that is guarded by a test, not by lint.
    ignores: ["dist", "supabase/functions", "src/integrations/supabase"],
  },
  {
    extends: [js.configs.recommended, ...tseslint.configs.recommended],
    files: ["**/*.{ts,tsx}"],
    languageOptions: {
      ecmaVersion: 2020,
      globals: globals.browser,
    },
    plugins: {
      "react-hooks": reactHooks,
      "react-refresh": reactRefresh,
    },
    rules: {
      ...reactHooks.configs.recommended.rules,
      "react-refresh/only-export-components": ["warn", { allowConstantExport: true }],
      "@typescript-eslint/no-unused-vars": "off",
    },
  },
);
