// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@2.0.4";

// src/lib/mcp/tools/classify-body-shape.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@2.0.4";
import { z } from "npm:zod@^3.25.76";

// src/lib/fit/shape.ts
var CM_PER_IN = 2.54;
var SPOON_RATIO = 1.193;
var toIn = (v, unit) => unit === "in" ? v : v / CM_PER_IN;
var round1 = (v) => Math.round(v * 10) / 10;
function classifyShape(m) {
  const unit = m.unit ?? "cm";
  const bust = toIn(m.bust, unit);
  const waist = toIn(m.waist, unit);
  const hips = toIn(m.hips, unit);
  const highHip = m.highHip === void 0 ? void 0 : toIn(m.highHip, unit);
  const bustHips = bust - hips;
  const hipsBust = hips - bust;
  const bustWaist = bust - waist;
  const hipsWaist = hips - waist;
  const diffs = {
    bustHips: round1((bust - hips) * CM_PER_IN),
    bustWaist: round1((bust - waist) * CM_PER_IN),
    hipsWaist: round1((hips - waist) * CM_PER_IN)
  };
  const merged = highHip === void 0;
  const highHipRatio = highHip === void 0 ? void 0 : highHip / waist;
  const done = (shape, rule) => ({
    shape,
    merged: merged && (shape === "bottom-hourglass" || shape === "spoon"),
    rule,
    diffs
  });
  if (bustHips <= 1 && hipsBust < 3.6 && (bustWaist >= 9 || hipsWaist >= 10)) {
    return done("hourglass", "ffit.hourglass");
  }
  if (hipsBust >= 3.6 && hipsBust < 10 && hipsWaist >= 9 && (highHipRatio === void 0 || highHipRatio < SPOON_RATIO)) {
    return done("bottom-hourglass", "ffit.bottomHourglass");
  }
  if (bustHips > 1 && bustHips < 10 && bustWaist >= 9) {
    return done("top-hourglass", "ffit.topHourglass");
  }
  if (highHipRatio !== void 0 && hipsBust > 2 && hipsWaist >= 7 && highHipRatio >= SPOON_RATIO) {
    return done("spoon", "ffit.spoon");
  }
  if (hipsBust >= 3.6 && hipsWaist >= 0 && hipsWaist < 9) {
    return done("triangle", "ffit.triangle");
  }
  if (bustHips >= 3.6 && bustWaist < 9 && hipsWaist >= 0) {
    return done("inverted-triangle", "ffit.invertedTriangle");
  }
  if (hipsWaist < 0 && bustWaist < 0) {
    return done("diamond", "ffit.diamond");
  }
  if (hipsWaist < 0 && bustWaist >= 0) {
    return done("oval", "ffit.oval");
  }
  return done("rectangle", "ffit.rectangle");
}

// src/lib/mcp/tools/classify-body-shape.ts
var classify_body_shape_default = defineTool({
  name: "classify_body_shape",
  title: "Classify body proportions",
  description: "Classify body proportions into an FFIT proportion label (hourglass, spoon, triangle, rectangle, ...) from bust, waist and hips. Returns the label, the rule that fired and the differences in cm. Descriptive arithmetic only \u2014 never an aesthetic judgement, and never weight, BMI or health.",
  inputSchema: {
    bust: z.number().positive().describe("Bust circumference."),
    waist: z.number().positive().describe("Waist circumference."),
    hips: z.number().positive().describe("Hip circumference."),
    highHip: z.number().positive().optional().describe("Upper hip, ~7-10 cm below the waist. Only needed to tell spoon from bottom-hourglass."),
    unit: z.enum(["cm", "in"]).optional().describe("Unit of the measurements. Defaults to cm.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ bust, waist, hips, highHip, unit }) => {
    const result = classifyShape({ bust, waist, hips, highHip, unit });
    const d = result.diffs;
    const text = d ? `Proportion label: ${result.shape} (rule ${result.rule}). Bust minus hips ${d.bustHips.toFixed(1)} cm, bust minus waist ${d.bustWaist.toFixed(1)} cm, hips minus waist ${d.hipsWaist.toFixed(1)} cm.${result.merged ? " Upper hip was missing, so spoon and bottom-hourglass are merged." : ""}` : `Proportion label: ${result.shape} (rule ${result.rule}).`;
    return { content: [{ type: "text", text }], structuredContent: { ...result } };
  }
});

// src/lib/mcp/tools/search-products.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@2.0.4";
import { z as z2 } from "npm:zod@^3.25.76";

// src/data/mockData.ts
var productMaterials = {
  "1": {
    composition: [{ name: "Linen", percent: 70, natural: true }, { name: "Cotton", percent: 30, natural: true }],
    qualityScore: 88
  },
  "2": {
    composition: [{ name: "Viscose", percent: 100, natural: false }],
    qualityScore: 65
  },
  "3": {
    composition: [{ name: "Organic Cotton", percent: 98, natural: true }, { name: "Elastane", percent: 2, natural: false }],
    qualityScore: 82
  },
  "4": {
    composition: [{ name: "Wool", percent: 80, natural: true }, { name: "Polyester", percent: 20, natural: false }],
    qualityScore: 91
  },
  "5": {
    composition: [{ name: "Silk", percent: 100, natural: true }],
    qualityScore: 95
  },
  "6": {
    composition: [{ name: "Polyester", percent: 65, natural: false }, { name: "Viscose", percent: 30, natural: false }, { name: "Elastane", percent: 5, natural: false }],
    qualityScore: 55
  },
  "7": {
    composition: [{ name: "Genuine Leather", percent: 100, natural: true }],
    qualityScore: 85
  },
  "8": {
    composition: [{ name: "Satin (Polyester)", percent: 100, natural: false }],
    qualityScore: 60
  },
  "9": {
    composition: [{ name: "Wool", percent: 55, natural: true }, { name: "Cotton", percent: 40, natural: true }, { name: "Elastane", percent: 5, natural: false }],
    qualityScore: 89
  },
  "10": {
    composition: [{ name: "Cotton", percent: 50, natural: true }, { name: "Polyester", percent: 50, natural: false }],
    qualityScore: 45
  },
  "13": {
    composition: [{ name: "Acrylic", percent: 80, natural: false }, { name: "Polyester", percent: 20, natural: false }],
    qualityScore: 35
  },
  "14": {
    composition: [{ name: "Linen", percent: 55, natural: true }, { name: "Cotton", percent: 40, natural: true }, { name: "Elastane", percent: 5, natural: false }],
    qualityScore: 84
  },
  "15": {
    composition: [{ name: "Organic Cotton", percent: 95, natural: true }, { name: "Elastane", percent: 5, natural: false }],
    qualityScore: 78
  },
  "17": {
    composition: [{ name: "Cotton", percent: 98, natural: true }, { name: "Elastane", percent: 2, natural: false }],
    qualityScore: 75
  },
  "20": {
    composition: [{ name: "Cotton", percent: 100, natural: true }],
    qualityScore: 83
  }
};
var allProducts = [
  { id: "1", name: "Linen Midi Dress", brand: "H&M", price: 129, fitScore: 94, category: "dresses", isSecondHand: false, store: "H&M" },
  { id: "2", name: "Floral Wrap Dress", brand: "Mango", price: 139, fitScore: 92, category: "dresses", isSecondHand: false, store: "Mango" },
  { id: "3", name: "Cotton Midi Skirt", brand: "Arket", price: 89, fitScore: 91, category: "skirts", isSecondHand: false, store: "Arket" },
  { id: "4", name: "Oversized Blazer", brand: "COS", price: 349, fitScore: 97, category: "outerwear", isSecondHand: false, store: "COS" },
  { id: "5", name: "Silk Camisole", brand: "& Other Stories", price: 189, fitScore: 90, category: "tops", isSecondHand: false, store: "& Other Stories" },
  { id: "6", name: "Wide Trousers", brand: "Zara", price: 179, fitScore: 93, category: "bottoms", isSecondHand: false, store: "Zara" },
  { id: "7", name: "Leather Mules", brand: "Vinted", price: 85, fitScore: 88, category: "shoes", isSecondHand: true, store: "Vinted" },
  { id: "8", name: "Satin Midi Dress", brand: "Vinted", price: 65, fitScore: 89, category: "dresses", isSecondHand: true, store: "Vinted" },
  { id: "9", name: "Tailored Vest", brand: "Massimo Dutti", price: 259, fitScore: 95, category: "tops", isSecondHand: false, store: "Massimo Dutti" },
  { id: "10", name: "Knit Polo Top", brand: "Reserved", price: 59, fitScore: 86, category: "tops", isSecondHand: false, store: "Reserved" },
  { id: "11", name: "Pleated Maxi Skirt", brand: "H&M", price: 99, fitScore: 91, category: "skirts", isSecondHand: false, store: "H&M" },
  { id: "12", name: "Boho Print Dress", brand: "Vinted", price: 45, fitScore: 87, category: "dresses", isSecondHand: true, store: "Vinted" },
  { id: "13", name: "Cropped Cardigan", brand: "Sinsay", price: 49, fitScore: 83, category: "tops", isSecondHand: false, store: "Sinsay" },
  { id: "14", name: "Linen Blend Blazer", brand: "Mango", price: 199, fitScore: 93, category: "outerwear", isSecondHand: false, store: "Mango" },
  { id: "15", name: "Ribbed Tank Top", brand: "Arket", price: 69, fitScore: 90, category: "tops", isSecondHand: false, store: "Arket" },
  { id: "16", name: "A-Line Mini Dress", brand: "Reserved", price: 79, fitScore: 85, category: "dresses", isSecondHand: false, store: "Reserved" },
  { id: "17", name: "High-Waist Jeans", brand: "H&M", price: 119, fitScore: 92, category: "bottoms", isSecondHand: false, store: "H&M" },
  { id: "18", name: "Slip Dress", brand: "Vinted", price: 55, fitScore: 86, category: "dresses", isSecondHand: true, store: "Vinted" },
  { id: "19", name: "Structured Tote Bag", brand: "Massimo Dutti", price: 299, fitScore: 0, category: "accessories", isSecondHand: false, store: "Massimo Dutti" },
  { id: "20", name: "Cotton Poplin Shirt", brand: "& Other Stories", price: 149, fitScore: 91, category: "tops", isSecondHand: false, store: "& Other Stories" },
  { id: "21", name: "Summer Wedding Dress", brand: "H&M", price: 139, fitScore: 94, category: "dresses", isSecondHand: false, store: "H&M" },
  { id: "22", name: "Garden Party Dress", brand: "Mango", price: 119, fitScore: 92, category: "dresses", isSecondHand: false, store: "Mango" },
  { id: "23", name: "Flowy Midi Dress", brand: "Vinted", price: 75, fitScore: 89, category: "dresses", isSecondHand: true, store: "Vinted" },
  { id: "24", name: "Wrap Midi Dress", brand: "Vinted", price: 60, fitScore: 85, category: "dresses", isSecondHand: true, store: "Vinted" },
  { id: "25", name: "Pastel Midi Dress", brand: "Reserved", price: 99, fitScore: 88, category: "dresses", isSecondHand: false, store: "Reserved" },
  { id: "26", name: "Eyelet Lace Dress", brand: "H&M", price: 149, fitScore: 91, category: "dresses", isSecondHand: false, store: "H&M" },
  { id: "27", name: "Tiered Maxi Dress", brand: "Sinsay", price: 89, fitScore: 79, category: "dresses", isSecondHand: false, store: "Sinsay" },
  { id: "28", name: "Boho Wrap Dress", brand: "Vinted", price: 50, fitScore: 86, category: "dresses", isSecondHand: true, store: "Vinted" },
  { id: "29", name: "Smocked Midi Dress", brand: "Mango", price: 129, fitScore: 90, category: "dresses", isSecondHand: false, store: "Mango" },
  { id: "30", name: "Ruffle Hem Dress", brand: "Vinted", price: 42, fitScore: 82, category: "dresses", isSecondHand: true, store: "Vinted" }
];
var weddingProducts = allProducts.filter((p) => p.category === "dresses" && p.price <= 150).sort((a2, b) => b.fitScore - a2.fitScore);
var vintedOnlyProducts = weddingProducts.filter((p) => p.isSecondHand);
var sampleCollections = [
  { id: "1", name: "Fall faves", items: allProducts.slice(0, 6), emoji: "\u{1F342}" },
  { id: "2", name: "Winter layers", items: allProducts.slice(3, 8), emoji: "\u2744\uFE0F" },
  { id: "3", name: "Going out", items: allProducts.slice(5, 10), emoji: "\u2728" },
  { id: "4", name: "Holiday wishlist", items: allProducts.slice(0, 12), emoji: "\u{1F384}" }
];
var chatStates = [
  // State 0 - greeting (empty, greeting shown as header)
  [],
  // State 1 - user searches, Paula asks about occasion type with detailed chips
  [
    { id: "u1", sender: "user", text: "Summer wedding dress, max 150 PLN" },
    { id: "p1", sender: "paula", text: "Great! Tell me more about the wedding \u2014 I'll help match the style to the occasion.", chips: ["Garden / outdoor wedding", "Church, elegant", "Banquet hall", "Beach wedding", "Rustic wedding", "Civil / intimate ceremony"] }
  ],
  // State 2 - user picks garden, Paula asks about length + style details
  [
    { id: "u1", sender: "user", text: "Summer wedding dress, max 150 PLN" },
    { id: "p1", sender: "paula", text: "Great! Tell me more about the wedding \u2014 I'll help match the style to the occasion." },
    { id: "u2", sender: "user", text: "Garden / outdoor wedding" },
    { id: "p2", sender: "paula", text: "A garden \u2014 lovely! What length do you prefer? With your proportions, midi and maxi would work well.", chips: ["Midi (knee-length)", "Maxi (ankle-length)", "Mini", "Asymmetric", "No preference"] }
  ],
  // State 3 - user picks midi, Paula asks about color/pattern preferences
  [
    { id: "u1", sender: "user", text: "Summer wedding dress, max 150 PLN" },
    { id: "p1", sender: "paula", text: "Great! Tell me more about the wedding \u2014 I'll help match the style to the occasion." },
    { id: "u2", sender: "user", text: "Garden / outdoor wedding" },
    { id: "p2", sender: "paula", text: "A garden \u2014 lovely! What length do you prefer? With your proportions, midi and maxi would work well." },
    { id: "u3", sender: "user", text: "Midi (knee-length)" },
    { id: "p3", sender: "paula", text: "What colors or patterns are you drawn to?", chips: ["Floral", "Pastels", "Solid color", "Satin / shimmer", "Something bold", "I'll show you options"] }
  ],
  // State 4 - user picks floral, results appear
  [
    { id: "u1", sender: "user", text: "Summer wedding dress, max 150 PLN" },
    { id: "p1", sender: "paula", text: "Great! Tell me more about the wedding \u2014 I'll help match the style to the occasion." },
    { id: "u2", sender: "user", text: "Garden / outdoor wedding" },
    { id: "p2", sender: "paula", text: "A garden \u2014 lovely! What length do you prefer? With your proportions, midi and maxi would work well." },
    { id: "u3", sender: "user", text: "Midi (knee-length)" },
    { id: "p3", sender: "paula", text: "What colors or patterns are you drawn to?" },
    { id: "u4", sender: "user", text: "Floral" },
    { id: "p4", sender: "paula", text: `I found ${weddingProducts.length} options that match your body and the occasion. Want to narrow it down?`, chips: ["New only", "Second-hand only", "Free shipping", "Show all"] }
  ],
  // State 5 - user filters second hand
  [
    { id: "u1", sender: "user", text: "Summer wedding dress, max 150 PLN" },
    { id: "p1", sender: "paula", text: "Great! Tell me more about the wedding \u2014 I'll help match the style to the occasion." },
    { id: "u2", sender: "user", text: "Garden / outdoor wedding" },
    { id: "p2", sender: "paula", text: "A garden \u2014 lovely! What length do you prefer? With your proportions, midi and maxi would work well." },
    { id: "u3", sender: "user", text: "Midi (knee-length)" },
    { id: "p3", sender: "paula", text: "What colors or patterns are you drawn to?" },
    { id: "u4", sender: "user", text: "Floral" },
    { id: "p4", sender: "paula", text: `I found ${weddingProducts.length} options that match your body and the occasion. Want to narrow it down?` },
    { id: "u5", sender: "user", text: "Second-hand only" },
    { id: "p5", sender: "paula", text: `Filtering to second-hand \u2014 ${vintedOnlyProducts.length} items from Vinted. I can also search other platforms.`, chips: ["Show OLX too", "Vinted only", "Back to all"] }
  ],
  // State 6 - user uploads photo
  [
    { id: "u1", sender: "user", text: "Summer wedding dress, max 150 PLN" },
    { id: "p1", sender: "paula", text: "Great! Tell me more about the wedding \u2014 I'll help match the style to the occasion." },
    { id: "u2", sender: "user", text: "Garden / outdoor wedding" },
    { id: "p2", sender: "paula", text: "A garden \u2014 lovely! What length do you prefer? With your proportions, midi and maxi would work well." },
    { id: "u3", sender: "user", text: "Midi (knee-length)" },
    { id: "p3", sender: "paula", text: "What colors or patterns are you drawn to?" },
    { id: "u4", sender: "user", text: "Floral" },
    { id: "p4", sender: "paula", text: `I found ${weddingProducts.length} options that match your body and the occasion. Want to narrow it down?` },
    { id: "u5", sender: "user", text: "Second-hand only" },
    { id: "p5", sender: "paula", text: `Filtering to second-hand \u2014 ${vintedOnlyProducts.length} items from Vinted.` },
    { id: "u6", sender: "user", text: "Looking for something similar", photoUploaded: true },
    { id: "p6", sender: "paula", text: "I see a boho-style dress with a floral pattern \u2014 searching for similar ones that match your proportions.", chips: ["Exactly this pattern", "Similar cut, different color", "Show more boho", "Change style"] }
  ]
];

// src/lib/mcp/tools/search-products.ts
var search_products_default = defineTool2({
  name: "search_products",
  title: "Search the catalogue",
  description: "Search Paula's public product catalogue by free text, category and maximum price in PLN. Returns product id, name, brand, price and store.",
  inputSchema: {
    query: z2.string().trim().optional().describe("Free text matched against product name and brand."),
    category: z2.enum(["dresses", "tops", "bottoms", "skirts", "outerwear", "shoes", "accessories"]).optional().describe("Restrict to one category."),
    maxPrice: z2.number().positive().optional().describe("Maximum price in PLN."),
    limit: z2.number().int().min(1).max(50).optional().describe("Maximum number of results. Defaults to 10.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ query, category, maxPrice, limit }) => {
    const needle = query?.toLowerCase() ?? "";
    const items = allProducts.filter((p) => category ? p.category === category : true).filter((p) => maxPrice ? p.price <= maxPrice : true).filter(
      (p) => needle ? `${p.name} ${p.brand} ${p.category}`.toLowerCase().includes(needle) : true
    ).slice(0, limit ?? 10).map((p) => ({
      id: p.id,
      name: p.name,
      brand: p.brand,
      price: p.price,
      currency: "PLN",
      category: p.category,
      store: p.store,
      secondHand: p.isSecondHand
    }));
    const text = items.length ? items.map((p) => `${p.id}. ${p.name} \u2014 ${p.brand}, ${p.price} PLN (${p.category})`).join("\n") : "No products matched.";
    return { content: [{ type: "text", text }], structuredContent: { items } };
  }
});

// src/lib/mcp/tools/score-product-fit.ts
import { defineTool as defineTool3, ToolError } from "npm:@lovable.dev/mcp-js@2.0.4";
import { z as z3 } from "npm:zod@^3.25.76";

// src/lib/fit/score.ts
var WEIGHTS = {
  bust: 20,
  waist: 20,
  hips: 25,
  thighs: 15,
  stomach: 20
};
var POINTS = ["bust", "waist", "hips", "thighs", "stomach"];
var TIGHT_BASELINE = {
  "hourglass": {},
  "bottom-hourglass": { hips: 0.6, thighs: 0.4 },
  "top-hourglass": { bust: 0.6 },
  "spoon": { hips: 0.7, thighs: 0.6 },
  "triangle": { hips: 0.6, thighs: 0.4 },
  "inverted-triangle": { bust: 0.6 },
  "rectangle": { stomach: 0.4 },
  "diamond": { stomach: 0.7, waist: 0.6 },
  "oval": { stomach: 0.6, waist: 0.4 }
};
var LOOSE_BASELINE = {
  "hourglass": { waist: 0.5, stomach: 0.3 },
  "bottom-hourglass": { waist: 0.3 },
  "top-hourglass": { hips: 0.3 },
  "spoon": { waist: 0.3 },
  "triangle": { bust: 0.3 },
  "inverted-triangle": { hips: 0.4 },
  "rectangle": {},
  "diamond": {},
  "oval": {}
};
var clamp = (v) => Math.max(0, Math.min(1, v));
var isMeasurements = (b) => "bust" in b;
function computeFit(attrs, body) {
  const shape = isMeasurements(body) ? classifyShape(body).shape : body.shape;
  const stretch = attrs.stretchLevel?.value ?? "unknown";
  const silhouette = attrs.silhouette?.value;
  const waistDef = attrs.waistDefinition?.value;
  const rise = attrs.rise?.value;
  const closure = attrs.closureType?.value;
  const points = POINTS.map((point) => {
    const reasons = [];
    let tight = TIGHT_BASELINE[shape][point] ?? 0;
    let loose = LOOSE_BASELINE[shape][point] ?? 0;
    if (tight > 0) reasons.push(`shape.${shape}.tight.${point}`);
    if (loose > 0) reasons.push(`shape.${shape}.loose.${point}`);
    if (silhouette === "fitted") {
      if (tight > 0) {
        tight += 0.2;
        reasons.push("garment.fitted.amplifies");
      }
      loose = Math.max(0, loose - 0.2);
    }
    if (silhouette === "a-line" || silhouette === "flared") {
      if ((point === "hips" || point === "thighs") && tight > 0) {
        tight -= 0.35;
        reasons.push("garment.flared.relieves");
      }
    }
    if (silhouette === "oversized") {
      tight = Math.max(0, tight - 0.4);
      loose += 0.25;
      if (loose > 0) reasons.push("garment.oversized.loose");
    }
    if (silhouette === "wrap" && point === "waist") {
      loose = Math.max(0, loose - 0.4);
      reasons.push("garment.wrap.definesWaist");
    }
    if (silhouette === "empire" && point === "stomach") {
      tight = Math.max(0, tight - 0.3);
      reasons.push("garment.empire.skimsStomach");
    }
    if ((waistDef === "natural" || waistDef === "high") && point === "waist" && loose > 0) {
      loose -= 0.3;
      reasons.push("garment.definedWaist.closesGap");
    }
    if (waistDef === "elasticated" && (point === "waist" || point === "stomach")) {
      tight = Math.max(0, tight - 0.25);
      reasons.push("garment.elasticated.adapts");
    }
    if (rise === "high" && point === "stomach" && tight > 0) {
      tight -= 0.15;
      reasons.push("garment.highRise.smooths");
    }
    if (closure === "buttons" && point === "bust" && tight > 0) {
      tight += 0.2;
      reasons.push("garment.buttons.gape");
    }
    if (stretch === "high") {
      tight = Math.max(0, tight - 0.45);
      if (tight > 0 || reasons.length) reasons.push("fabric.stretch.high");
    } else if (stretch === "low") {
      tight = Math.max(0, tight - 0.2);
      if (tight > 0 || reasons.length) reasons.push("fabric.stretch.low");
    } else if (stretch === "none") {
      if (tight > 0) reasons.push("fabric.stretch.none");
    }
    tight = clamp(tight);
    loose = clamp(loose);
    const knowsGarment = silhouette !== void 0 || stretch !== "unknown";
    let verdict;
    if (!knowsGarment && tight === 0 && loose === 0) {
      verdict = "unknown";
      reasons.push("data.missingAttributes");
    } else if (tight >= 0.3 && tight >= loose) {
      verdict = "tight";
    } else if (loose >= 0.3) {
      verdict = "loose";
    } else {
      verdict = "neutral";
    }
    return { point, verdict, risk: Math.max(tight, loose), reasons };
  });
  const penalty = points.reduce((sum, p) => sum + p.risk * WEIGHTS[p.point], 0);
  const score = Math.round(100 - penalty);
  const known = [
    attrs.silhouette,
    attrs.stretchLevel,
    attrs.waistDefinition,
    attrs.rise,
    attrs.closureType
  ].filter(Boolean);
  const confidence = known.length === 0 ? 0.2 : Math.min(1, 0.2 + known.reduce((s, a2) => s + a2.confidence, 0) / 5 * 0.8);
  return { score, confidence: Math.round(confidence * 100) / 100, shape, points };
}

// src/lib/catalog/fibers.ts
var ALIASES = {
  linen: /\b(len|lnu|lnian\w*|linen|flax)\b/,
  cotton: /\b(baweln\w*|bawelny|cotton|coton)\b/,
  viscose: /\b(wiskoz\w*|viscose|rayon)\b/,
  modal: /\b(modal\w*)\b/,
  lyocell: /\b(lyocell|liocel\w*|tencel)\b/,
  wool: /\b(welna|welny|welnian\w*|wool|merino|merynos\w*)\b/,
  cashmere: /\b(kaszmir\w*|cashmere)\b/,
  silk: /\b(jedwab\w*|silk)\b/,
  polyester: /\b(poliester\w*|poliestr\w*|polyester)\b/,
  polyamide: /\b(poliamid\w*|polyamide|nylon\w*)\b/,
  acrylic: /\b(akryl\w*|acrylic|acryl)\b/,
  elastane: /\b(elastan\w*|elastane|elasthan\w*|spandex|lycra)\b/,
  leather: /\b(skor[ay]|skorzan\w*|leather|suede|zamsz\w*)\b/,
  // Faux leather, and the coating on most Polish high-street shoes and bags.
  // Zara names it outright — "100% poliuretan" — and without this the whole
  // composition read as nothing at all.
  polyurethane: /\b(poliuretan\w*|polyurethane|pu|tpu|ekoskor\w*|eko-skor\w*)\b/
};
var FIBERS = {
  linen: {
    id: "linen",
    nameKey: "fiberLinen",
    behaviorKey: "fiberLinenBehavior",
    natural: true,
    breathability: 95,
    abrasion: 80,
    pillingResistance: 90,
    wash: "warm",
    tumbleDry: false,
    iron: "high"
  },
  cotton: {
    id: "cotton",
    nameKey: "fiberCotton",
    behaviorKey: "fiberCottonBehavior",
    natural: true,
    breathability: 85,
    abrasion: 70,
    pillingResistance: 70,
    wash: "warm",
    tumbleDry: true,
    iron: "high"
  },
  viscose: {
    id: "viscose",
    nameKey: "fiberViscose",
    behaviorKey: "fiberViscoseBehavior",
    natural: false,
    breathability: 75,
    abrasion: 45,
    pillingResistance: 40,
    wash: "cold",
    tumbleDry: false,
    iron: "low"
  },
  modal: {
    id: "modal",
    nameKey: "fiberModal",
    behaviorKey: "fiberModalBehavior",
    natural: false,
    breathability: 80,
    abrasion: 60,
    pillingResistance: 65,
    wash: "warm",
    tumbleDry: true,
    iron: "medium"
  },
  lyocell: {
    id: "lyocell",
    nameKey: "fiberLyocell",
    behaviorKey: "fiberLyocellBehavior",
    natural: false,
    breathability: 85,
    abrasion: 70,
    pillingResistance: 70,
    wash: "warm",
    tumbleDry: true,
    iron: "medium"
  },
  wool: {
    id: "wool",
    nameKey: "fiberWool",
    behaviorKey: "fiberWoolBehavior",
    natural: true,
    breathability: 80,
    abrasion: 75,
    pillingResistance: 45,
    wash: "hand",
    tumbleDry: false,
    iron: "low"
  },
  cashmere: {
    id: "cashmere",
    nameKey: "fiberCashmere",
    behaviorKey: "fiberCashmereBehavior",
    natural: true,
    breathability: 80,
    abrasion: 50,
    pillingResistance: 25,
    wash: "hand",
    tumbleDry: false,
    iron: "low"
  },
  silk: {
    id: "silk",
    nameKey: "fiberSilk",
    behaviorKey: "fiberSilkBehavior",
    natural: true,
    breathability: 80,
    abrasion: 45,
    pillingResistance: 75,
    wash: "hand",
    tumbleDry: false,
    iron: "low"
  },
  polyester: {
    id: "polyester",
    nameKey: "fiberPolyester",
    behaviorKey: "fiberPolyesterBehavior",
    natural: false,
    breathability: 30,
    abrasion: 90,
    pillingResistance: 50,
    wash: "warm",
    tumbleDry: true,
    iron: "low"
  },
  polyamide: {
    id: "polyamide",
    nameKey: "fiberPolyamide",
    behaviorKey: "fiberPolyamideBehavior",
    natural: false,
    breathability: 35,
    abrasion: 92,
    pillingResistance: 60,
    wash: "warm",
    tumbleDry: true,
    iron: "low"
  },
  acrylic: {
    id: "acrylic",
    nameKey: "fiberAcrylic",
    behaviorKey: "fiberAcrylicBehavior",
    natural: false,
    breathability: 35,
    abrasion: 55,
    pillingResistance: 20,
    wash: "warm",
    tumbleDry: false,
    iron: "low"
  },
  elastane: {
    id: "elastane",
    nameKey: "fiberElastane",
    behaviorKey: "fiberElastaneBehavior",
    natural: false,
    breathability: 30,
    abrasion: 60,
    pillingResistance: 70,
    wash: "cold",
    tumbleDry: false,
    iron: "low"
  },
  leather: {
    id: "leather",
    nameKey: "fiberLeather",
    behaviorKey: "fiberLeatherBehavior",
    natural: true,
    breathability: 40,
    abrasion: 90,
    pillingResistance: 100,
    wash: "dryClean",
    tumbleDry: false,
    iron: "none"
  },
  polyurethane: {
    id: "polyurethane",
    nameKey: "fiberPolyurethane",
    behaviorKey: "fiberPolyurethaneBehavior",
    // A coating, not a woven fibre: it does not breathe and it does not pill,
    // and it gives up long before leather does — the crease that goes white
    // and then splits is the whole story of a PU jacket's second winter.
    natural: false,
    breathability: 5,
    abrasion: 45,
    pillingResistance: 100,
    wash: "hand",
    tumbleDry: false,
    iron: "none"
  }
};
function foldToAscii(text) {
  return text.toLowerCase().replace(/ł/g, "l").normalize("NFD").replace(/[\u0300-\u036f]/g, "");
}
function matchFiber(fragment) {
  const folded = foldToAscii(fragment);
  for (const id of Object.keys(ALIASES)) {
    if (ALIASES[id].test(folded)) return id;
  }
  return null;
}

// src/lib/catalog/composition.ts
var PERCENT = /(\d+(?:[.,]\d+)?)\s*%/g;
var WORDS = /[\p{L}][\p{L} -]*/gu;
function parseComposition(input) {
  if (input == null) return [];
  if (Array.isArray(input)) {
    return input.map((part) => {
      const fiber = matchFiber(part.name);
      return {
        fiber,
        label: part.name,
        percent: part.percent,
        natural: fiber ? FIBERS[fiber].natural : null
      };
    });
  }
  const text = input.trim();
  if (!text) return [];
  const percents = [];
  for (const match of text.matchAll(PERCENT)) {
    percents.push({
      value: parseFloat(match[1].replace(",", ".")),
      at: match.index ?? 0,
      taken: false
    });
  }
  const found = [];
  for (const match of text.matchAll(WORDS)) {
    const label = match[0].trim();
    const fiber = matchFiber(label);
    if (!fiber) continue;
    if (found.some((f) => f.fiber === fiber)) continue;
    const at = match.index ?? 0;
    found.push({ fiber, label, at, end: at + match[0].length });
  }
  if (found.length === 0) return [];
  const entries = found.map(({ fiber, label, at, end }) => {
    const before = percents.filter((p) => !p.taken && p.at < at).sort((a2, b) => b.at - a2.at)[0];
    const after = percents.filter((p) => !p.taken && p.at >= end).sort((a2, b) => a2.at - b.at)[0];
    const chosen = before ?? after;
    if (chosen) chosen.taken = true;
    return {
      fiber,
      label,
      percent: chosen ? chosen.value : null,
      natural: FIBERS[fiber].natural
    };
  });
  if (entries.length === 1 && entries[0].percent === null && percents.length === 0) {
    entries[0].percent = 100;
  }
  return entries;
}

// src/lib/fit/stretch.ts
var KNIT = /(knit|jersey|rib(bed)?|dzianina|prazkowan)/i;
function parseStretch(composition) {
  if (composition == null) {
    return { level: "unknown", confidence: 0, elastanePercent: null };
  }
  const text = Array.isArray(composition) ? composition.map((c) => `${c.percent}% ${c.name}`).join(", ") : composition;
  if (!text.trim()) {
    return { level: "unknown", confidence: 0, elastanePercent: null };
  }
  const elastic = parseComposition(composition).find((entry) => entry.fiber === "elastane");
  const percent = elastic?.percent ?? null;
  if (elastic && percent !== null) {
    return {
      level: percent >= 4 ? "high" : percent >= 1 ? "low" : "none",
      confidence: 0.9,
      elastanePercent: percent
    };
  }
  if (elastic) {
    return { level: "low", confidence: 0.5, elastanePercent: null };
  }
  if (KNIT.test(text)) {
    return { level: "low", confidence: 0.5, elastanePercent: null };
  }
  return { level: "none", confidence: 0.8, elastanePercent: null };
}

// src/data/fitAttributes.ts
var a = (value, confidence = 0.6) => ({ value, confidence });
var productFitAttributes = {
  // 1 Linen Midi Dress
  "1": { silhouette: a("straight"), waistDefinition: a("natural"), lengthClass: a("midi"), sleeveLength: a("sleeveless"), neckline: a("square") },
  // 2 Floral Wrap Dress
  "2": { silhouette: a("wrap"), waistDefinition: a("natural"), lengthClass: a("midi"), sleeveLength: a("short"), neckline: a("v"), closureType: a("wrap-tie") },
  // 3 Cotton Midi Skirt
  "3": { silhouette: a("a-line"), waistDefinition: a("natural"), rise: a("high"), lengthClass: a("midi"), closureType: a("zip") },
  // 4 Oversized Blazer
  "4": { silhouette: a("oversized"), waistDefinition: a("none"), sleeveLength: a("long"), closureType: a("buttons") },
  // 5 Silk Camisole
  "5": { silhouette: a("straight"), waistDefinition: a("none"), sleeveLength: a("sleeveless"), neckline: a("v") },
  // 6 Wide Trousers
  "6": { silhouette: a("flared"), rise: a("high"), lengthClass: a("full"), closureType: a("zip") },
  // 8 Satin Midi Dress
  "8": { silhouette: a("straight"), waistDefinition: a("none"), lengthClass: a("midi"), sleeveLength: a("sleeveless"), neckline: a("v") },
  // 9 Tailored Vest
  "9": { silhouette: a("fitted"), waistDefinition: a("natural"), sleeveLength: a("sleeveless"), neckline: a("v"), closureType: a("buttons") },
  // 10 Knit Polo Top — composition says cotton/poly, but a knit polo stretches
  "10": { silhouette: a("fitted"), waistDefinition: a("none"), sleeveLength: a("short"), closureType: a("buttons"), stretchLevel: a("low", 0.7) },
  // 11 Pleated Maxi Skirt
  "11": { silhouette: a("flared"), waistDefinition: a("high"), rise: a("high"), lengthClass: a("maxi"), closureType: a("zip") },
  // 12 Boho Print Dress
  "12": { silhouette: a("empire"), waistDefinition: a("high"), lengthClass: a("maxi"), sleeveLength: a("long"), neckline: a("v") },
  // 13 Cropped Cardigan — acrylic knit
  "13": { silhouette: a("fitted"), waistDefinition: a("none"), lengthClass: a("cropped"), sleeveLength: a("long"), closureType: a("buttons"), stretchLevel: a("low", 0.7) },
  // 14 Linen Blend Blazer
  "14": { silhouette: a("straight"), waistDefinition: a("none"), sleeveLength: a("long"), closureType: a("buttons") },
  // 15 Ribbed Tank Top — 5% elastane in the composition, stretch comes from there
  "15": { silhouette: a("fitted"), waistDefinition: a("none"), sleeveLength: a("sleeveless"), neckline: a("scoop") },
  // 16 A-Line Mini Dress
  "16": { silhouette: a("a-line"), waistDefinition: a("natural"), lengthClass: a("mini"), sleeveLength: a("short"), neckline: a("crew"), closureType: a("zip") },
  // 17 High-Waist Jeans — 2% elastane in the composition
  "17": { silhouette: a("fitted"), rise: a("high"), lengthClass: a("full"), closureType: a("zip") },
  // 18 Slip Dress
  "18": { silhouette: a("straight"), waistDefinition: a("none"), lengthClass: a("midi"), sleeveLength: a("sleeveless"), neckline: a("v") },
  // 20 Cotton Poplin Shirt
  "20": { silhouette: a("straight"), waistDefinition: a("none"), sleeveLength: a("long"), closureType: a("buttons") },
  // 21 Summer Wedding Dress
  "21": { silhouette: a("a-line"), waistDefinition: a("natural"), lengthClass: a("midi"), sleeveLength: a("sleeveless"), neckline: a("v"), closureType: a("zip") },
  // 22 Garden Party Dress
  "22": { silhouette: a("flared"), waistDefinition: a("natural"), lengthClass: a("midi"), sleeveLength: a("short"), neckline: a("square"), closureType: a("zip") },
  // 23 Flowy Midi Dress
  "23": { silhouette: a("flared"), waistDefinition: a("none"), lengthClass: a("midi"), sleeveLength: a("three-quarter"), neckline: a("v") },
  // 24 Wrap Midi Dress
  "24": { silhouette: a("wrap"), waistDefinition: a("natural"), lengthClass: a("midi"), sleeveLength: a("short"), neckline: a("v"), closureType: a("wrap-tie") },
  // 25 Pastel Midi Dress
  "25": { silhouette: a("straight"), waistDefinition: a("natural"), lengthClass: a("midi"), sleeveLength: a("short"), neckline: a("crew"), closureType: a("zip") },
  // 26 Eyelet Lace Dress
  "26": { silhouette: a("a-line"), waistDefinition: a("natural"), lengthClass: a("midi"), sleeveLength: a("short"), neckline: a("square"), closureType: a("zip") },
  // 27 Tiered Maxi Dress
  "27": { silhouette: a("flared"), waistDefinition: a("none"), lengthClass: a("maxi"), sleeveLength: a("sleeveless"), neckline: a("v") },
  // 28 Boho Wrap Dress
  "28": { silhouette: a("wrap"), waistDefinition: a("natural"), lengthClass: a("maxi"), sleeveLength: a("long"), neckline: a("v"), closureType: a("wrap-tie") },
  // 29 Smocked Midi Dress — smocked bodice stretches
  "29": { silhouette: a("fitted"), waistDefinition: a("elasticated"), lengthClass: a("midi"), sleeveLength: a("short"), neckline: a("square"), stretchLevel: a("low", 0.7) },
  // 30 Ruffle Hem Dress
  "30": { silhouette: a("a-line"), waistDefinition: a("natural"), lengthClass: a("mini"), sleeveLength: a("short"), neckline: a("v"), closureType: a("zip") },
  // Boho search results (bohoProducts)
  "b1": { silhouette: a("flared"), waistDefinition: a("none"), lengthClass: a("maxi"), sleeveLength: a("long"), neckline: a("v") },
  "b2": { silhouette: a("oversized"), waistDefinition: a("none"), lengthClass: a("midi"), sleeveLength: a("three-quarter"), neckline: a("v") },
  "b3": { silhouette: a("fitted"), waistDefinition: a("none"), lengthClass: a("midi"), sleeveLength: a("sleeveless"), neckline: a("scoop"), stretchLevel: a("low", 0.7) },
  "b4": { silhouette: a("flared"), waistDefinition: a("elasticated"), lengthClass: a("midi"), sleeveLength: a("short"), neckline: a("off-shoulder") },
  "b5": { silhouette: a("flared"), waistDefinition: a("none"), lengthClass: a("maxi"), sleeveLength: a("sleeveless"), neckline: a("v") },
  "b6": { silhouette: a("wrap"), waistDefinition: a("natural"), lengthClass: a("midi"), sleeveLength: a("long"), neckline: a("v"), closureType: a("wrap-tie") }
};

// src/lib/mcp/tools/score-product-fit.ts
var SHAPES = [
  "hourglass",
  "bottom-hourglass",
  "top-hourglass",
  "spoon",
  "triangle",
  "inverted-triangle",
  "rectangle",
  "diamond",
  "oval"
];
var score_product_fit_default = defineTool3({
  name: "score_product_fit",
  title: "Score fit risk for a product",
  description: "Estimate fit risk per body point (bust, waist, hips, thighs, stomach) for one catalogue product, from measurements or a proportion label. Returns a score, a confidence and a tight/loose/neutral verdict with reason codes per point. This is fit risk, not an aesthetic judgement.",
  inputSchema: {
    productId: z3.string().trim().min(1).describe("Product id from search_products."),
    bust: z3.number().positive().optional().describe("Bust circumference in cm."),
    waist: z3.number().positive().optional().describe("Waist circumference in cm."),
    hips: z3.number().positive().optional().describe("Hip circumference in cm."),
    highHip: z3.number().positive().optional().describe("Upper hip in cm, optional."),
    shape: z3.enum(SHAPES).optional().describe("Proportion label, used instead of measurements when they are not available.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ productId, bust, waist, hips, highHip, shape }) => {
    const product = allProducts.find((p) => p.id === productId);
    if (!product) throw new ToolError(`No product with id "${productId}".`);
    const attrs = productFitAttributes[productId];
    if (!attrs) {
      throw new ToolError(
        `Product "${product.name}" carries no fit attributes, so no fit risk can be computed for it.`
      );
    }
    let body;
    if (bust && waist && hips) body = { bust, waist, hips, highHip };
    else if (shape) body = { shape };
    else throw new ToolError("Provide bust, waist and hips together, or a shape.");
    const material = productMaterials[productId]?.composition;
    const stretch = material ? parseStretch(material) : null;
    const withStretch = stretch ? { ...attrs, stretchLevel: { value: stretch.level, confidence: stretch.confidence } } : attrs;
    const result = computeFit(withStretch, body);
    const lines = result.points.map(
      (p) => `${p.point}: ${p.verdict} (risk ${Math.round(p.risk * 100)}%) [${p.reasons.join(", ") || "no reason codes"}]`
    );
    const text = [
      `${product.name} \u2014 ${product.brand}, ${product.price} PLN`,
      `Fit score ${result.score}, confidence ${Math.round(result.confidence * 100)}%`,
      ...lines
    ].join("\n");
    return {
      content: [{ type: "text", text }],
      structuredContent: {
        product: { id: product.id, name: product.name, brand: product.brand, price: product.price },
        fit: {
          score: result.score,
          confidence: result.confidence,
          points: result.points.map((p) => ({
            point: p.point,
            verdict: p.verdict,
            risk: p.risk,
            reasons: [...p.reasons]
          }))
        }
      }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "remix-of-stylist-paula",
  title: "Remix of Stylist Paula",
  version: "0.1.0",
  instructions: "Tools for Paula, a fit-first fashion app for the Polish market (prices in PLN). Use `classify_body_shape` to turn bust/waist/hip measurements into a proportion label, `search_products` to browse the public catalogue, and `score_product_fit` to estimate fit risk per body point for one product. Describe cut and arithmetic only, as the tool results do; evaluative or prescriptive phrasing about the body is out of scope, and so is any statement about weight, diet, health or age.",
  tools: [classify_body_shape_default, search_products_default, score_product_fit_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@2.0.4/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
